apiVersion: v1
kind: Service
metadata:
  name: liferay-jpda-service
  labels:
    name: liferay
spec:
  type: NodePort
  ports:
  - nodePort: 30953
    port: 8000
    protocol: TCP
    targetPort: 8080
  selector:
    app: liferay

---

apiVersion: v1
kind: Service
metadata:
  name: liferay-gogo-service
  labels:
    name: liferay
spec:
  type: NodePort
  ports:
  - nodePort: 30952
    port: 11311
    protocol: TCP
    targetPort: 11311
  selector:
    app: liferay

---

apiVersion: v1
kind: Service
metadata:
  name: liferay-np-service
  labels:
    name: liferay
spec:
  type: NodePort
  ports:
  - nodePort: 30951
    port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: liferay
---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app: liferay-data
  name: liferay-data
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi


---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app: liferay-config
  name: liferay-config
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app: liferay-osgi
  name: liferay-osgi
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 3Gi

---

apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: liferay
  name: liferay
spec:
  replicas: 1 #Inicialmente crearemos 1 pod de este deployment
  selector:
    matchLabels:
      app: liferay
  strategy:
    type: RollingUpdate #Usaremos rollingupdate con el fin de disponer de zero-downtime
  template:
    metadata:
      labels:
        app: liferay
    spec:
      containers:
      - env: 
        - name: LIFERAY_JAVA_OPTS 
          value: -Xms2g -Xmx2g
        - name: LIFERAY_MODULE_PERIOD_FRAMEWORK_PERIOD_PROPERTIES_PERIOD_OSGI_PERIOD_CONSOLE
          value: 0.0.0.0:11311
        - name: LIFERAY_WEB_PERIOD_SERVER_PERIOD_DISPLAY_PERIOD_NODE #La usaremos con el fin de probar el cluster
          value: "true"
        - name: LIFERAY_REDIRECT_PERIOD_URL_PERIOD_SECURITY_PERIOD_MODE #La usaremos para permitir los redirect en el cluster
          value: "domain"
        name: dxp
        image: liferay/dxp
        #imagePullPolicy: Never
        #resources:
        #  requests: #Recursos que se aprovisionan al memomento de arrancar el pod
        #    memory: "2048Mi"
        #    cpu: "1"
        #  limits: #Limite de recursos que podrá disponer el pod
        #    memory: "4098Mi"
        #    cpu: "1"
        ports: #puertos abiertos en el contenedor
        - containerPort: 11311
        - containerPort: 8080
        - containerPort: 8000
        readinessProbe: # permite controlar si el pod esta con capacidad de dar servicio, si no tiene capacidad k8s detiene el trafico a el
          httpGet:
            path: "/c/portal/layout"
            port: 8080
          initialDelaySeconds: 100
          periodSeconds: 30
          failureThreshold: 3
          successThreshold: 3
        #livenessProbe: # Permite controlar cuando el pod se considera vivo y se mete en en balanceador. Si falla, reinicia el pod
        #  tcpSocket:
        #    port: 8080
        #  initialDelaySeconds: 120
        #  periodSeconds: 20
        #  failureThreshold: 3
        #  successThreshold: 1
        volumeMounts: # directorios donde se van a montar los volumenes
        - mountPath: /opt/liferay/data
          name: liferay-data
        - mountPath: /mnt/liferay
          name: liferay-config
        - mountPath: /opt/liferay/osgi2
          name: liferay-osgi
      restartPolicy: Always #politica de reinicio ante errores en el contenedor
      volumes: # descripcion de los volumenes y pvc
      - name: liferay-data
        persistentVolumeClaim:
          claimName: liferay-data
      - name: liferay-config
        persistentVolumeClaim:
          claimName: liferay-config
      - name: liferay-osgi
        persistentVolumeClaim:
          claimName: liferay-osgi