apiVersion: v1
kind: Service
metadata:
  name: postgres-service
  labels:
    name: postgres
spec:
  type: NodePort
  ports:
  - nodePort: 30950
    port: 5432
    protocol: TCP
    targetPort: 5432
  selector:
    app: postgres

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app: postgres-data
  name: postgres-data
spec:
  storageClassName: manual
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
      
      
---


apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: postgres
  name: postgres
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
        - name: postgres
          image: postgres:11.10
          env:
          - name: PGDATA
            value: /var/lib/postgresql/data/pgdata
          - name: POSTGRES_USER
            value: lportal
          - name: POSTGRES_PASSWORD
            value: lportal
          - name: POSTGRES_DB
            value: lportal
          ports:
          - containerPort: 5432
          volumeMounts:
          - mountPath: /var/lib/postgresql/data
            name: postgres-data
          #restartPolicy: Always
        #resources:
        #  limits:
        #    memory: "512Mi"
        #    cpu: "0.5"
      volumes:
      - name: postgres-data
        persistentVolumeClaim:
          claimName: postgres-data
